### ISSUE TITLE
Handle HTML Mails

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/python-zimbra-web#50]
HTML Mails are not accepted by Zimbra, so they should be detected and returned as undeliverable

**Comment by frereit** [comment]
All this needs to do is return `Response(success=False, status='HTML-Emails werden nicht unterstützt')`. The SMTP Bridge will then detect a failure and bounce the email back once cirosec-studis/zimbraweb-smtp-bridge#20 is fixed.

**Comment by JM-Lemmi** [comment]
Add a configurable option to allow html E-Mails to be sent via Backup SMTP cirosec-studis/zimbraweb-smtp-bridge#16

**Comment by frereit** [comment]
Closed by #56 (not supported)
