### ISSUE TITLE
Handle multiple different bodies and choose the right type in `multipart_eml_parsing`

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/python-zimbra-web#56]
This will simply set the body to the last non-attachment body. In attachmentmail.eml outlook generated a `multipart/mixed` payload which contains both HTML and text/plain messages. We should just always choose to only send text/plain if possible, otherwise bounce.

_Originally posted by @frereit in https://github.com/cirosec-studis/python-zimbra-web/pull/54#discussion_r745875936_

**Comment by JM-Lemmi** [comment]
Is it an issue, that sometimes the plain body is not really the same as the html body and we just string the html?

The example [here](https://www.phpclasses.org/browse/file/14672.html) has a plain body, that just says, that the message is in html! But we strip the html if there is a plain body.

```
--69c1683a3ee16ef7cf16edd700694a2f
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

This is an HTML message. Please use an HTML capable mail program to read
this message.

--69c1683a3ee16ef7cf16edd700694a2f
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<title>Testing Manuel Lemos' MIME E-mail composing and sending PHP class: H=
TML message</title>
```

**Comment by frereit** [comment]
Hmm, that's not ideal. Maybe we should reject all mail that's not text/plain + attachments? That is doable with [pymilter](https://github.com/sdgathman/pymilter), I'm working on adding that to the Dockerfile right now.

It might be a good idea to add a new function the emlparsing module `can_parse(eml)` that does not require a user session and just returns True or False based on if the EML can be parsed or not. That would make it possible to check the emails before accepting them with postfix.

**Comment by JM-Lemmi** [comment]
Yes, thats a good idea. Right now I would accept this as a not supported edgecase. Just like HTML mails this should be put on the not-supported list.
