### ISSUE TITLE
add `can_parse(eml)` for filtering in the milter

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/python-zimbra-web#57]
It might be a good idea to add a new function the emlparsing module `can_parse(eml)` that does not require a user session and just returns True or False based on if the EML can be parsed or not. That would make it possible to check the emails before accepting them with postfix.

_Originally posted by @frereit in https://github.com/cirosec-studis/python-zimbra-web/issues/56#issuecomment-965171662_

**Comment by frereit** [comment]
Closed by #61 

This is now done via try.. except:
```python
try:
    zimbraweb.emlparsing.parse_eml(emlstr)
except UnsupportedEMLError:
    print("invalid eml")
```
