### ISSUE TITLE
Pass Message ID to Zimbra to prevent confusion in Client

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/python-zimbra-web#62]

**Comment by frereit** [comment]
Can you elaborate on this? I don't really understand what the issue is about tbh

**Comment by JM-Lemmi** [comment]
When sending from Outlook for example, Outlook will put the message it sent into the 'Sent' Folder with the ID Outlook gave the message. The actually sent message in Zimbra will get a different ID, "duplicating" the Message in the Client Interface. Same for responses or E-Mail-Thread display in Outlook. The response will contain a different Message-ID as related than what Outlook knows.

This is not a huge issue, but iirc there was a Message-ID Field in the Request to Zimbra which is just empty.

**Comment by frereit** [comment]
Ok, gotcha. I think we can't fix this, sadly. Zimbra only uses the supplied message id to check if that message has already been received and then overwrites it with its own. I disabled the "save a copy to my sent folder" option in thunderbird to fix the duplication issue.
